### ISSUE TITLE
dynamicAddProperty打印出来有2个和你文章里面打印不一致是什么原因？

### ISSUE THREAD

**Issue by yoowei** [lizelu/ObjCRuntimeDemo#1]
这里只有一个dynamicAddProperty属性
@interface TestClass (AssociatedObject)
@property (nonatomic, strong) NSString *dynamicAddProperty;
@end

为什么打印出来有2个dynamicAddProperty
2017-03-14 10:53:50.184064 ObjCRuntimeDemo[10829:242568] 
获取TestClass的属性列表:(
    dynamicAddProperty,
    dynamicAddProperty,
    privateProperty1,
    privateProperty2,
    privateProperty3,
    publicProperty1,
    publicProperty2
)

跟您文章里面的也不一致：不知为什么？请您指点一下，谢谢

**Comment by lizelu** [comment]
你好，谢谢指出，代码已更正，已提交到github上，请更新。出现上述情况的原因是在属性关联的延展中，将@implementation放到了.h中，导致了上述问题~
